name: Notify On Issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN1 }}
  
jobs:
  slack-message:
    runs-on: ubuntu-latest

    steps:
    - name: Send Slack Message
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,author,ref,workflow 
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} 
      if: always() # Pick up events even if the job fails or is canceled.
