name: Notify on issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN1 }}
  
jobs:
  slack-message:
    runs-on: ubuntu-latest

    steps:
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }} 
        notification_title: '{workflow} has {status_message}'
        message_format: ' {status_message} in <{repo_url}|{repo}>'
        footer: 'Linked to Repo <{repo_url}|{repo}>'
        
      env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
       
