name: Notify On Issue

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN1 }}
  
jobs:
  slack-message:
    runs-on: ubuntu-latest

    steps:
    - name: Report Status
      if: always()
      uses: ravsamhq/notify-slack-action@v1
      with:
        status: ${{ job.status }}
        notify_when: 'failure' 
      env:
       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
       
