
name: Nodeapp CI

on:
 push:
    branches: [develop, master]
 pull_request:
    branches: [develop, master]
    
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        repository: freelearn2000/Project1
        path: ./nodeapp
         
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        repository: freelearn2000/Project1
        path: ./nodeapp
        
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('nodeapp/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
           
        
    - name: Install dependencies
      run: npm ci
      working-directory: ./nodeapp  
      
    - name: Do Code Analysis
      run: echo "Do code analysis here..."

    - name: Upload Code coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: codeanalysis_coverage
      #   path: codecoverage
      run: echo "Upload code analysis coverage here..."

    #- name: Run Tests
    #  run: npm run test

    - name: Upload Test coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: test_coverage
      #   path: testcoverage
      run: echo "Upload test coverage here..."
        
    - name: Build project
      if: github.event_name == 'push'
      run: echo "Build the project here..."
      #run: npm run build
      #working-directory: ./nodeapp
     
    - name: Upload Build folder as Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build
