name: Nodeapp CI

on:
 push:
    branches: [develop, master]
 pull_request:
    branches: [develop, master]
      
env:
  NODE_VERSION: '14.x'                                             # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
            
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
       
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('nodeapp/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
       
    - name: Install dependencies NodeApp
      run: npm install
      working-directory: ./nodeapp
         
    - name: Do Code Analysis NodeApp
      run: echo "Do code analysis here..."

    - name: Upload Code coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: codeanalysis_coverage_react
      #   path: ./reactapp/codecoverage
      run: echo "Upload code analysis coverage here..."

    - name: Run Tests
      run: npm run test
      working-directory: ./nodeapp

    - name: Upload Test coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: test_coverage_react
      #   path: ./reactapp/testcoverage
      run: echo "Upload test coverage here..."
        
    - name: Build project Node
      if: github.event_name == 'push'
      run: npm run build --if-present
      working-directory: ./nodeapp

    - name: Upload React Build folder as Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: ./nodeapp/build
       
   
    - name: Create Issue Action
      if: ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Automated Issue from project1
        token: ${{secrets.SEMANTIC_TOKEN1}}
        assignees: ${{GITHUB_ACTOR}}
        labels: workflow-failed
        body: This issue was automatically created for test failing(project1) ${{github.sha}}
        
    - name: echo-default-env-variables
      run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
