name: PostgreSQL for GitHub Actions

on:
  [workflow_dispatch]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/postgresql@v1
      with:
        server-name: "infrapostgres.postgres.database.azure.com"
        connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
        plsql-file: "database/schemafile.sql"

# Azure logout 
    #- name: logout
     # run: |
     #   az logout
