name: PostgreSQL for GitHub Actions

on:
   [workflow_dispatch]

jobs:
build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - uses: azure/postgresql@v1
      with:
    server-name: POSTGRESQL_SERVER_NAME
    connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
    sql-file: './data.sql'

    # Azure logout
 #- name: logout
 # run: |
     #az logout
