name: Reactapp CI

on:
 push:
    branches: [develop, master]
 pull_request:
    branches: [develop, master]
      
env:
  NODE_VERSION: '14.x'                                             # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        repository: freelearn2000/Project1
        path: ./reactapp
            
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        repository: freelearn2000/Project1
        path: ./reactapp
        node-version: ${{ env.NODE_VERSION }}
       
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('reactapp/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
           
    - name: Install dependencies
      run: npm install
      working-directory: ./reactapp
         
    - name: Do Code Analysis
      run: echo "Do code analysis here..."

    - name: Upload Code coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: codeanalysis_coverage
      #   path: codecoverage
      run: echo "Upload code analysis coverage here..."

    - name: Run Tests
      run: npm run test
      working-directory: ./reactapp

    - name: Upload Test coverage as Artifact
      # uses: actions/upload-artifact@v2
      # with:
      #   name: test_coverage_react
      #   path: ./reactapp/testcoverage
      run: echo "Upload test coverage here..."
        
    - name: Build project React
      if: github.event_name == 'push'
      run: npm run build --if-present
      working-directory: ./reactapp

    - name: Upload React Build folder as Artifact
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: ./reactapp/build
       
   
    - name: Send message to Slack API
      uses: rtCamp/action-slack-notify@v2
      env:
       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
       SLACK_LINK_NAMES: true

        
    - name: echo-default-env-variables
      run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"

  
       
       
