name: Create Release 

# Trigger the create release workflow
on:
  workflow_run:
     workflows: ["Nodeapp","Reactapp"]
     types: [completed]
     branches: [master]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion== 'success' }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
            
    - name: Setup Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    #- name: Download from Node artifact
    #  uses: actions/download-artifact@v3
    #  with:
    #    name: Node_build
    #     path: ./nodeapp/build
         
    - name: Download from React artifact
      uses: actions/download-artifact@v3
      with:
         name: React Build
         path: ./reactapp/build

    - name: Add Build Assets for Release
      if: github.event_name == 'workflow_run' && github.ref == 'refs/heads/master'
      run: |
         zip -r Node_build.zip build
         zip -r React_build.zip build
      
    - name: Create a Release
      run: npx semantic-release
      env:
         GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN1 }}
             
  
      

    
